### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by MartinCodes0** [aleskxyz/haproxy-ipv6-demux#2]
سلام وقت بخیر. ممنون واسه این پروژه.
من به مشکل خوردم. سرور خارج مستقیم جواب میده. پینگ هم میتونم بگیرم با آروان از کل سابنت سرور هتزنر. ولی وقتی با کانفیگ از کلاینت که میخوام وصل بشم از طریق سرور ایران, نمیتونم. timeout میده. ممنون میشم بگی چیکار میشه کرد, چیزی به ذهنم نمیرسه, طبق آموزش رفتم.

P.S: به جز اون لطفا بگو دامین خارج و ایران و تنظیمات سینگ باکس خارج رو چطوری تنظیم کردی.

**Comment by aleskxyz** [comment]
این راه حل برای اونایی مناسبه که اشراف کامل روی مباحث سیستم عامل و شبکه و سرویسهاش دارن و میتونن اون رو عیب یابی کنن. هیچ تضمینی نیست که با اجرای این دستورات حتما همه چی کار کنه و نیازی به یه سری تغییرات به وسیله شما نباشه.
این مشکلی که شما مطرح کردید خیلی کلی هست و نمیشه دقیقا گفت مشکل چیه.
ولی شما قبل از اینکه بخواین با کلاینت تست کنید اول مطمین بشید که این راه کار داره کار میکنه. مثلا سعی کنید با دستور curl ببینید که درخواست از سرور داخل ایران جواب میده یا نه
